"""baseline schema

Revision ID: ccdc13958bcb
Revises: 
Create Date: 2026-05-29 15:18:55.376697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccdc13958bcb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ADVISOR', 'CLIENT', name='userrole'), nullable=False),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('azure_oid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cases',
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='casestatus'), nullable=False),
    sa.Column('compact_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('case_id')
    )
    # Circular FK users.case_id -> cases.case_id, added now that both tables exist
    # (modelled with use_alter=True; op.create_table omits it, so add it explicitly).
    op.create_foreign_key('fk_users_case_id', 'users', 'cases', ['case_id'], ['case_id'])
    op.create_table('invite_tokens',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('kb_review_queue',
    sa.Column('entry_id', sa.String(), nullable=False),
    sa.Column('jurisdiction', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('web_url', sa.String(), nullable=False),
    sa.Column('date_retrieved', sa.DateTime(), nullable=False),
    sa.Column('current_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'RESUBMITTED', 'RE_REJECTED', name='reviewstatus'), nullable=False),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_note', sa.Text(), nullable=True),
    sa.Column('resubmission_note', sa.Text(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.create_table('case_decks',
    sa.Column('deck_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('spec_json', sa.Text(), nullable=False),
    sa.Column('spec_hash', sa.String(length=64), nullable=False),
    sa.Column('pptx_path', sa.String(), nullable=True),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('generated_by', sa.String(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('deck_id')
    )
    op.create_index(op.f('ix_case_decks_case_id'), 'case_decks', ['case_id'], unique=False)
    op.create_table('case_diagrams',
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('nodes_json', sa.Text(), nullable=False),
    sa.Column('edges_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('client_profiles',
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('domicile', sa.String(), nullable=True),
    sa.Column('tax_residency', sa.String(), nullable=True),
    sa.Column('family_members', sa.Text(), nullable=True),
    sa.Column('asset_classes', sa.Text(), nullable=True),
    sa.Column('asset_jurisdictions', sa.Text(), nullable=True),
    sa.Column('existing_structures', sa.Text(), nullable=True),
    sa.Column('objectives', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('profile_id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('conversations',
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources_cited', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('documents',
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_type', sa.Enum('TXT', 'PDF', 'DOCX', name='filetype'), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('parsed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('recommendations',
    sa.Column('recommendation_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('structure_name', sa.String(), nullable=False),
    sa.Column('confidence_level', sa.Enum('HIGH', 'SPECIALIST_REVIEW', 'COMPLEX', name='confidencelevel'), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('sources', sa.Text(), nullable=False),
    sa.Column('diagram_data', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_case_id', 'users', type_='foreignkey')
    op.drop_table('recommendations')
    op.drop_table('documents')
    op.drop_table('conversations')
    op.drop_table('client_profiles')
    op.drop_table('case_diagrams')
    op.drop_index(op.f('ix_case_decks_case_id'), table_name='case_decks')
    op.drop_table('case_decks')
    op.drop_table('kb_review_queue')
    op.drop_table('invite_tokens')
    op.drop_table('cases')
    op.drop_table('users')
    op.drop_table('system_settings')
    # Native PG enum types are not auto-dropped with their tables.
    for _enum in ('userrole', 'casestatus', 'reviewstatus', 'messagerole', 'filetype', 'confidencelevel'):
        op.execute(f'DROP TYPE IF EXISTS {_enum}')
    # ### end Alembic commands ###
